### ISSUE TITLE
IT: Create Account 

### ISSUE THREAD

**Issue by misslame** [LetsMesh/IntegrationTests#1]
Create a basic account and test all error handling functionalities. 

Test the following with integration tests: 

- [ ] Fill out forms
- [ ] Navigate through steps
- [ ] Create Account 
- [ ] Confirm Account has been created 
- [ ] Test endpoint with a GET that confirms the account was created.
