### ISSUE TITLE
IT: Open Settings

### ISSUE THREAD

**Issue by misslame** [LetsMesh/IntegrationTests#10]
Open up Settings panel and ensure that all defined settings are present

- [ ] Toggle dark theme present and accessible
- [ ] Change password present and accessible
- [ ] Change email present and accessible
- [ ] Activate 2 factor 
- [ ] Deactivate Account present and accessible
- [ ] Connect 3rd party account present and accessible
