### ISSUE TITLE
IT: Add / Change Occupation

### ISSUE THREAD

**Issue by misslame** [LetsMesh/IntegrationTests#15]
Test various inputs around Occupation(s)

- [ ] Add an Occupation
- [ ] Add Past occupations
- [ ] Remove an occupation
