### ISSUE TITLE
IT: Add/ Change Education

### ISSUE THREAD

**Issue by misslame** [LetsMesh/IntegrationTests#16]
Test the input around Education 

- [ ] Add an Education
- [ ] Change an Existing Education 
- [ ] Delete a previous Education
