### ISSUE TITLE
IT: Login

### ISSUE THREAD

**Issue by misslame** [LetsMesh/IntegrationTests#2]
Login with an account that was already created and ensure it is correct account as well as given expected error handling & messaging. 

Test the following with integration tests: 

- [ ] Login on the home screen
- [ ] Login on the login screen
- [ ] Use Failed credentials -> expect failure
