### ISSUE TITLE
IT: Forgot Password 

### ISSUE THREAD

**Issue by misslame** [LetsMesh/IntegrationTests#4]
Confirm the functionality around forgot password

Test the following with integration tests: 

- [ ] Forget password Home Screen-> Request new password
- [ ] Forget password Login Screen-> Request new password
- [ ] Provide email that doesn't exist
- [ ] provide email that exists
