### ISSUE TITLE
IT: Change Profile Picture

### ISSUE THREAD

**Issue by misslame** [LetsMesh/IntegrationTests#6]
Test the following with integration tests: 

- [ ] Change profile picture
- [ ] Remove profile picture (reset to default)
- [ ] Add new profile picture
- [ ] confirm changes
